### ISSUE TITLE
How to deal with an encryption key

### ISSUE THREAD

**Issue by chof747** [aquaticus/esphome-iec62056#1]
My smart meter sends the data encrypted with an AES key I have. How do I configure the component to also use such a key?

Thx Christian

**Comment by aquaticus** [comment]
You can't.
Your meter uses different standard. Probably DMSL.
By the way, did you get encryption key from energy supplier?

**Comment by chof747** [comment]
Yes I did, and the website says both iec-62056 and DLMS/COSEM. Where could I find info for DLMS?

**Comment by aquaticus** [comment]
I saw ESPHome components but don't remember if any of them supported optical interface.
